name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: your-droplet-ip
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            cp -R $GITHUB_WORKSPACE/* .
